#!/usr/bin/python3
"""Factorizes as many numbers as possible into a product of two smaller numbers."""
import sys

with open(sys.argv[1], "r") as file:
    lines = file.readlines()
    numbers = [int(line) for line in lines]
    numbers.sort()

    for num in numbers:
        divisor = 2
        while divisor < num:
            if num % divisor == 0:
                factor = num // divisor
                print("{} = {} * {}".format(num, factor, divisor))
                break
            else:
                divisor += 1

