#!/usr/bin/python3
"""Factorize given set of numbers in a file into a product of two smaller numbers"""
from sys import argv
import time

def factorize(number_to_check):
    """Find two small numbers that multiply to give a given number"""
    i = 2

    if number_to_check < 2:
        return

    while number_to_check % i:
        i += 1
    print("{0}={1}*{2}".format(number_to_check, number_to_check // i, i))

if len(argv) != 2:
    print("Usage: factors <file>")
    exit(1)

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line:
            number_to_check = int(line.strip())
            factorize(number_to_check)
            line = file.readline()
except FileNotFoundError:
    print(f"File not found: {argv[1]}")
except Exception as e:
    print(f"An error occurred: {str(e)}")

# Ensure the program exits after 5 seconds
time.sleep(5)

