#!/usr/bin/env bash
# test a factors challenge

test_factor()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                countr=0
                numb2=1
                for a in ${args[*]};
                do
                        if [ $countr -gt 1 ];
                        then
                                numb2=$(echo $a*$numb2 | bc)
                        fi
                        countr=$((countr + 1))
                done
        else
                numb2=$3
        fi

        numb1=$2
        num=$(echo "$1" | tr ':' '=')

        result=$(echo "if($numb2 > $numb1) 1 else 0" | bc)
	        if ((result == 1)); then
		        numcp=$numb1
		        numb1=$numb2
		        numb2=$numcp
                fi

        echo "$num$numb1*$numb2"
}

if [ $# -ne 1 ]
then
        echo 'Usage: factors <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                test_factor $result

        done < "$1"
fi
